version: 2.1
jobs:
  test:
    environment:
      JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:8-jdk-stretch
        auth:
          username: chrimaeon
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Deps.kt"}}
      - run:
          name: Run tests
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Deps.kt"}}
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/reports
          when: always
workflows:
  version: 2
  workflow:
    jobs:
      - test:
          filters:
            branches:
              only:
                - develop
                - main
                - /release\/.*/
                - /hotfix\/.*/
