[versions]
kotlin = "1.7.22"
mockito = "4.9.0"
gradle = "7.6"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
intellij = "org.jetbrains.intellij:1.10.1"
changelog = "org.jetbrains.changelog:2.0.0"
depUpdates = "com.github.ben-manes.versions:0.44.0"
kover = "org.jetbrains.kotlinx.kover:0.6.1"

[libraries]
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin"}
proguard-retrace = "com.guardsquare:proguard-retrace:7.3.0"
okio = "com.squareup.okio:okio:3.2.0"
ktlint = "com.pinterest:ktlint:0.47.1"
junit-bom = "org.junit:junit-bom:5.9.1"
hamcrest = "org.hamcrest:hamcrest-library:2.2"
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit = { module =  "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }

[bundles]
mockito = ["mockito-core", "mockito-junit"]
