[versions]
kotlin = "1.6.21"
mockito = "4.5.1"
gradle = "7.4.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
intellij = "org.jetbrains.intellij:1.5.3"
changelog = "org.jetbrains.changelog:1.3.1"
depUpdates = "com.github.ben-manes.versions:0.42.0"
kover = "org.jetbrains.kotlinx.kover:0.5.1"

[libraries]
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin"}
proguard-retrace = "com.guardsquare:proguard-retrace:7.2.1"
okio = "com.squareup.okio:okio:3.1.0"
ktlint = "com.pinterest:ktlint:0.45.2"
junit-bom = "org.junit:junit-bom:5.8.2"
hamcrest = "org.hamcrest:hamcrest-library:2.2"
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit = { module =  "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }

[bundles]
mockito = ["mockito-core", "mockito-junit"]
