[versions]
kotlin = "2.3.20"
mockito = "5.22.0"
gradle = "9.2.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij = "org.jetbrains.intellij.platform:2.11.0"
changelog = "org.jetbrains.changelog:2.5.0"
depUpdates = "com.github.ben-manes.versions:0.53.0"
kover = "org.jetbrains.kotlinx.kover:0.9.7"

[libraries]
proguard-retrace = "com.guardsquare:proguard-retrace:7.8.2"
ktlint = "com.pinterest.ktlint:ktlint-cli:1.8.0"
junit-bom = "org.junit:junit-bom:6.0.3"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-junit = "junit:junit:4.13.2"
hamcrest = "org.hamcrest:hamcrest-library:3.0"
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
mockito-kotlin = "org.mockito.kotlin:mockito-kotlin:6.3.0"
google-r8 = "com.android.tools:r8:9.0.32"

[bundles]
mockito = [
    "mockito-core",
    "mockito-junit",
    "mockito-kotlin",
]
