name: Build & Test & Verify
on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
      - 'hotfix/**'
    tags:
      - '**'
  workflow_dispatch:
  pull_request:

jobs:
  checkAndUnitTest:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu

      - name: Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('**/build.gradle.kts', '**/Deps.kt') }}

      - name: Gradle Wrapper Cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle/wrapper
          key: gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Download dependencies
        run: ./gradlew dependencies

      - name: Build & Test
        run: ./gradlew check

      - name: Run Plugin Verifier
        run: ./gradlew runPluginVerifier

      - name: Archive Test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            build/reports/*
            build/test-results/*
      
